/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Siswa;

import SambungDB.sambungDatabase;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.DateFormat;

/**
 *
 * @author m16yusuf
 */
public class formSiswa extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuSiswa
     */
    String pattern ="yyyy-mm-dd";
    SimpleDateFormat tanggal = new SimpleDateFormat(pattern);
    
    public formSiswa() {
        initComponents();
    }
    
    public void tampilSiswa(){
        Object[] row = {"NIS ", "Nama Siswa","Alamat","Tanggal Lahir","Kelas"}; 
        DefaultTableModel tabmodel = new DefaultTableModel(null,row);
        JTableSiswa.setModel(tabmodel); 
        
        sambungDatabase sambung = new sambungDatabase();
        try{
            
            
            String sql = "SELECT * FROM tb_siswa";
            ResultSet res = sambung.stat.executeQuery(sql);
            while(res.next()){
                String nis = res.getString("nis");
                String nama_siswa = res.getString("nama_siswa");
                String alamat_siswa = res.getString("alamat_siswa");
                Date tanggal_lahir = res.getDate("tgl_lahir_siswa");
                String tgl_lahir_siswa = String.valueOf(tanggal.format(tanggal_lahir));
                String kelas = res.getString("id_kelas");
                
                
                String[] data = {nis,nama_siswa,alamat_siswa,tgl_lahir_siswa,kelas};
                tabmodel.addRow(data);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableSiswa = new javax.swing.JTable();
        TblCari = new javax.swing.JButton();
        TblRefresh = new javax.swing.JButton();
        TblTambah = new javax.swing.JButton();
        TblEdit = new javax.swing.JButton();
        TblHapus = new javax.swing.JButton();
        TblTutup = new javax.swing.JButton();

        jLabel1.setText("Data Siswa ");

        JTableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(JTableSiswa);

        TblCari.setText("Cari");
        TblCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblCariActionPerformed(evt);
            }
        });

        TblRefresh.setText("Refresh");
        TblRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblRefreshActionPerformed(evt);
            }
        });

        TblTambah.setText("Tambah");

        TblEdit.setText("Edit");

        TblHapus.setText("Hapus");

        TblTutup.setText("Tutup");
        TblTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(TblCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TblRefresh)
                    .addComponent(TblHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TblEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TblTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TblTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TblCari))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TblRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TblTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TblEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TblHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TblTutup)))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TblCariActionPerformed

    private void TblTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_TblTutupActionPerformed

    private void TblRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblRefreshActionPerformed
        // TODO add your handling code here:
        tampilSiswa();
    }//GEN-LAST:event_TblRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableSiswa;
    private javax.swing.JButton TblCari;
    private javax.swing.JButton TblEdit;
    private javax.swing.JButton TblHapus;
    private javax.swing.JButton TblRefresh;
    private javax.swing.JButton TblTambah;
    private javax.swing.JButton TblTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
