/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Siswa;

import SambungDB.sambungDatabase;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author m16yusuf
 */
public class formSiswa extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuSiswa
     */
    SimpleDateFormat tglinput = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat tglview = new SimpleDateFormat("dd-MM-yyyy");
    
    public formSiswa() {
        initComponents();
        cbKelasID();
    }
    
    private void cbKelasID(){
        sambungDatabase sambung = new sambungDatabase();
        try{
            String sql="select id_kelas from tb_kelas";
            ResultSet res = sambung.stat.executeQuery(sql);
            
           while(res.next()){
               String jenis =res.getString("id_kelas");
               CBKelas.addItem(jenis);
           }    
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        } 
    }
    
    
    public void tampilSiswa(){
        Object[] row = {"NIS ", "Nama Siswa","Alamat","Tanggal Lahir","Kelas"}; 
        DefaultTableModel tabmodel = new DefaultTableModel(null,row);
        JTableSiswa.setModel(tabmodel); 
  
        sambungDatabase sambung = new sambungDatabase();
        try{
            String sql = "SELECT * FROM tb_siswa";
            ResultSet res = sambung.stat.executeQuery(sql);
            while(res.next()){
                String nis = res.getString("nis");
                String nama_siswa = res.getString("nama_siswa");
                String alamat_siswa = res.getString("alamat_siswa");
                String tgl_lahir_siswa = tglview.format(res.getDate("tgl_lahir_siswa"));
                String kelas = res.getString("id_kelas");
                String[] data = {nis,nama_siswa,alamat_siswa,tgl_lahir_siswa,kelas};
                tabmodel.addRow(data);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableSiswa = new javax.swing.JTable();
        TblCari = new javax.swing.JButton();
        TblTutup = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TblRefresh = new javax.swing.JButton();
        TblTambah = new javax.swing.JButton();
        TblEdit = new javax.swing.JButton();
        TblHapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CBKelas = new javax.swing.JComboBox<>();
        TblFilterKelas = new javax.swing.JButton();

        jLabel1.setText("Data Siswa ");

        JTableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(JTableSiswa);

        TblCari.setText("Cari");
        TblCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblCariActionPerformed(evt);
            }
        });

        TblTutup.setText("Tutup");
        TblTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblTutupActionPerformed(evt);
            }
        });

        TblRefresh.setText("Refresh");
        TblRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblRefreshActionPerformed(evt);
            }
        });

        TblTambah.setText("Tambah");
        TblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblTambahActionPerformed(evt);
            }
        });

        TblEdit.setText("Edit");
        TblEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblEditActionPerformed(evt);
            }
        });

        TblHapus.setText("Hapus");
        TblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TblTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(TblRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TblEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TblHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TblRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TblTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TblEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TblHapus))
        );

        TblFilterKelas.setText("Filter");
        TblFilterKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblFilterKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TblFilterKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TblFilterKelas))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(153, 153, 153)
                        .addComponent(TblCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TblTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TblCari))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TblTutup)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblCariActionPerformed
        // TODO add your handling code here:
        Object[] row = {"NIS ", "Nama Siswa","Alamat","Tanggal Lahir","Kelas"}; 
        DefaultTableModel tabmodel = new DefaultTableModel(null,row);
        JTableSiswa.setModel(tabmodel); 
  
        sambungDatabase sambung = new sambungDatabase();
        try{
            String sql = "SELECT * FROM tb_siswa WHERE nis LIKE '%" 
                    +txtCari.getText()+ "%' or nama_siswa LIKE '%" +txtCari.getText()+
                    "%' or alamat_siswa LIKE '%" +txtCari.getText()+ "%'";
            ResultSet res = sambung.stat.executeQuery(sql);
            while(res.next()){
                String nis = res.getString("nis");
                String nama_siswa = res.getString("nama_siswa");
                String alamat_siswa = res.getString("alamat_siswa");
                String tgl_lahir_siswa = tglview.format(res.getDate("tgl_lahir_siswa"));
                String kelas = res.getString("id_kelas");
                String[] data = {nis,nama_siswa,alamat_siswa,tgl_lahir_siswa,kelas};
                tabmodel.addRow(data);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        }
    }//GEN-LAST:event_TblCariActionPerformed

    private void TblTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_TblTutupActionPerformed

    private void TblRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblRefreshActionPerformed
        // TODO add your handling code here:
        tampilSiswa();
    }//GEN-LAST:event_TblRefreshActionPerformed

    private void TblFilterKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblFilterKelasActionPerformed
        // TODO add your handling code here:
        Object[] row = {"NIS ", "Nama Siswa","Alamat","Tanggal Lahir","Kelas"}; 
        DefaultTableModel tabmodel = new DefaultTableModel(null,row);
        JTableSiswa.setModel(tabmodel); 
  
        sambungDatabase sambung = new sambungDatabase();
        try{
            String sql = "SELECT * FROM tb_siswa WHERE id_kelas LIKE '%" 
                    + CBKelas.getSelectedItem() + "%' ";
            ResultSet res = sambung.stat.executeQuery(sql);
            while(res.next()){
                String nis = res.getString("nis");
                String nama_siswa = res.getString("nama_siswa");
                String alamat_siswa = res.getString("alamat_siswa");
                String tgl_lahir_siswa = tglview.format(res.getDate("tgl_lahir_siswa"));
                String kelas = res.getString("id_kelas");
                String[] data = {nis,nama_siswa,alamat_siswa,tgl_lahir_siswa,kelas};
                tabmodel.addRow(data);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        }
    }//GEN-LAST:event_TblFilterKelasActionPerformed

    private void TblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblTambahActionPerformed
        // TODO add your handling code here:
        tambahSiswa tambah = new tambahSiswa();
        tambah.setVisible(true);
    }//GEN-LAST:event_TblTambahActionPerformed

    private void TblEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblEditActionPerformed
        // TODO add your handling code here:
        editSiswa edit = new editSiswa();
        edit.setVisible(true);
    }//GEN-LAST:event_TblEditActionPerformed

    private void TblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblHapusActionPerformed
        // TODO add your handling code here:
        hapusSiswa hapus = new hapusSiswa();
        hapus.setVisible(true);
    }//GEN-LAST:event_TblHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBKelas;
    private javax.swing.JTable JTableSiswa;
    private javax.swing.JButton TblCari;
    private javax.swing.JButton TblEdit;
    private javax.swing.JButton TblFilterKelas;
    private javax.swing.JButton TblHapus;
    private javax.swing.JButton TblRefresh;
    private javax.swing.JButton TblTambah;
    private javax.swing.JButton TblTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
