/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kelas;

import SambungDB.sambungDatabase;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author m16yusuf
 */
public class tambahKelas extends javax.swing.JFrame {

    /**
     * Creates new form tambahKelas
     */
    public tambahKelas() {
        initComponents();
        cbwalikelas();
    }
    
    private void cbwalikelas(){
        sambungDatabase sambung = new sambungDatabase();
        try{
            String sql="select * from tb_guru";
            ResultSet res = sambung.stat.executeQuery(sql);
            
           while(res.next()){
               String jenis =res.getString("nama_guru");
               CBwali.addItem(jenis);
           }    
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBwali = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnaddKelas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelNip = new javax.swing.JLabel();
        CBTingkatKelas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtIDKelas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Tingkat Kelas ");

        jLabel3.setText("Wali Kelas");

        CBwali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBwaliActionPerformed(evt);
            }
        });

        jLabel4.setText("Tambah Kelas");

        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnaddKelas.setText("Submit");
        btnaddKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddKelasActionPerformed(evt);
            }
        });

        jLabel5.setText("NIP");

        labelNip.setText("NIP");

        CBTingkatKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas 1", "Kelas 2", "Kelas 3", "Kelas 4", "Kelas 5", "Kelas 6" }));

        jLabel1.setText("ID Kelas");

        txtIDKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKelasKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnaddKelas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBwali, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBTingkatKelas, 0, 165, Short.MAX_VALUE)
                            .addComponent(txtIDKelas))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBTingkatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBwali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNip))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnaddKelas))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddKelasActionPerformed
        // TODO add your handling code here:
       sambungDatabase sambung = new sambungDatabase();
       int tingkat = 0;
       if(CBTingkatKelas.getSelectedItem()=="Kelas 1"){
           tingkat = 1;
       }
       else
       if (CBTingkatKelas.getSelectedItem()=="Kelas 2"){
           tingkat = 2;
       }
       else
       if (CBTingkatKelas.getSelectedItem()=="Kelas 3"){
           tingkat = 3;
       }
       else
       if (CBTingkatKelas.getSelectedItem()=="Kelas 4"){
           tingkat = 4;
       }
       else
       if (CBTingkatKelas.getSelectedItem()=="Kelas 5"){
           tingkat = 5;
       }
       else
       if (CBTingkatKelas.getSelectedItem()=="Kelas 6"){
           tingkat = 6;
       }
       
       try{
           String temp = txtIDKelas.getText();
           String sql ="INSERT INTO tb_kelas VALUES('" +temp.toUpperCase()+ "','" +tingkat+ "','" +labelNip.getText()+"')";
           sambung.stat.executeUpdate(sql);
           
           JOptionPane.showMessageDialog(null, "Data berhasil di tambahkan");
           dispose();
       }
       catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        } 
    }//GEN-LAST:event_btnaddKelasActionPerformed

    private void CBwaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBwaliActionPerformed
        // TODO add your handling code here:
        sambungDatabase sambung = new sambungDatabase();
        try{
            String sql = "SELECT * FROM tb_guru WHERE nama_guru= '"+ CBwali.getSelectedItem() +"' ";
            ResultSet res = sambung.stat.executeQuery(sql);
            while(res.next()){
                String nip_wali = res.getString("nip");
                labelNip.setText(nip_wali);
            }  
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        } 
    }//GEN-LAST:event_CBwaliActionPerformed

    private void txtIDKelasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKelasKeyReleased
        // TODO add your handling code here:
        sambungDatabase sambung = new sambungDatabase();
        String temp = txtIDKelas.getText();
        try{
            String sql = "SELECT id_kelas FROM tb_kelas WHERE id_kelas= '"+ txtIDKelas.getText() +"' ";
            ResultSet res = sambung.stat.executeQuery(sql);
            if(res.next()){
                if(txtIDKelas.getText().equalsIgnoreCase(res.getString("id_kelas"))){
                    JOptionPane.showMessageDialog(null, "ID Kelas tidak bisa digunakan atau sudah ada");
                    txtIDKelas.setText("");
                }  
            }  
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        } 
    }//GEN-LAST:event_txtIDKelasKeyReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBTingkatKelas;
    private javax.swing.JComboBox<String> CBwali;
    private javax.swing.JButton btnaddKelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelNip;
    private javax.swing.JTextField txtIDKelas;
    // End of variables declaration//GEN-END:variables
}
